### ISSUE TITLE
MacOS: change install directory/path

### ISSUE THREAD

**Issue by nickterhaar** [GertJan84/lms-rust-cli#11]
**Describe the bug**
When installing it is now installing inside a directory (.local/bin) that's not in the MacOS PATH by default.

**Expected behavior**
To make it as easy as possible to use, it should rather be installing inside "/usr/local/bin".
This directory is in the MacOS PATH by default.

**Desktop (please complete the following information):**
 - OS: MacOS/OSX

**Comment by GertJan84** [comment]
After consideration we decided not to implement this because of the default permission of this folder.
